import React from "react";
import type { Metadata } from "next";
import ModernizationSection from "./components/ModenizationSection";
import UnreleasedSection from "./components/UnreleasedSection";

export const metadata: Metadata = {
  title: "Contributions at Nagios | Taylor Steele",
  description: "Generated by create next app",
};

export default function Nagios() {

  return (
    <div className="flex flex-col items-center justify-between gap-8">
      <div className="flex flex-col gap-4 items-center leading-relaxed font-sourceCodePro text-secondaryText w-full">
        {/* Title & intro */}
        <div className="flex flex-col gap-3">
          <h1 className="text-3xl font-ibmPlexSerif text-primaryText font-semibold">
            Contributions at Nagios
          </h1>
          <p className="text-base leading-relaxed text-secondaryText">
            As a Web Developer at Nagios, I contributed to the development and
            optimization of multiple web platforms, including websites and
            experimental projects. My work focused on implementing modern,
            scalable solutions within WordPress/Elementor, along with developing
            prototypes in React-based environments. By collaborating with
            cross-functional teams, I ensured seamless integrations, performance
            optimizations, and user-friendly web experiences across all
            projects.
          </p>
        </div>

        <ModernizationSection />
        <hr className=" border-gray-500 border-opacity-40 w-1/3" />
        <UnreleasedSection />
      </div>
    </div>
  );
}
