import React from "react";
import type { Metadata } from "next";
import QRCodeGenerator from "@/components/qr-generator";

export const metadata: Metadata = {
  title: "Projects | Web Developer",
  description: "Generated by create next app",
};


export default function Projects() {
  return (
    <div className="flex flex-col items-start justify-between gap-8">
        <div className="flex flex-col gap-8 leading-relaxed font-sourceCodePro text-secondaryText w-full"
        >
          {/* What's cookin' & intro */}
           <div className="flex flex-col gap-3">
            <h1 className="text-2xl font-ibmPlexSerif text-primaryText font-semibold">What&apos;s cookin&apos;</h1>
            <p className="text-sm leading-relaxed text-primaryText">
            Here’s where I keep the things I’ve been working on — projects from the past (coming soon) and ideas I’m currently exploring. It’s all about continuous learning, growing, and building along the way.
            </p>
          </div>

          {/* Tools */}
          <div className="flex flex-col gap-3"> 
            <h2 className="font-ibmPlexSerif text-xl text-primaryText">Tools</h2>
            <p className="text-xs leading-relaxed text-secondaryText">
            These are tools I’ve put together to address everyday challenges. They’re built with usability in mind and designed to make life just a little bit easier.
            </p>
          </div>


          {/* QR Generator */}
          <div className="flex flex-col gap-3">
            <h3 className="font-ibmPlexSerif text-sm text-primaryText">QR Code Generator</h3>
            <p className="text-xs leading-relaxed text-secondaryText">
            A simple tool to generate QR codes. Enter a URL, click "Generate," and you’re good to go.
            </p>
            <QRCodeGenerator />
          </div>

        </div>
    </div>
  );
}
