import React from "react";
import type { Metadata } from "next";
import QRCodeGenerator from "@/components/qr-generator";

export const metadata: Metadata = {
  title: "Projects | Web Developer",
  description: "Generated by create next app",
};


export default function Projects() {
  return (
    <div className="flex flex-col items-start justify-between gap-8">
        <div className="flex flex-col gap-8 leading-relaxed font-sourceCodePro text-secondaryText w-full"
        >
          {/* What's cookin' & intro */}
           <div className="flex flex-col gap-3">
            <h1 className="text-2xl font-ibmPlexSerif text-primaryText font-semibold">What's cookin'</h1>
            <p>
              I am a dedicated and detail-oriented Web Developer with expertise in both front and back-end development. With a background in Digital Marketing Technology and a minor in Computer Science, I combine technical knowledge with marketing insight to deliver web solutions that are not only functional but also optimized for performance and SEO.
            </p>
          </div>

          {/* Tools */}
          <div className="flex flex-col gap-3"> 
            <h2 className="font-ibmPlexSerif text-xl text-primaryText">Tools</h2>
            <p>
              I thrive in collaborative environments, consistently working cross-functionally to ensure projects are delivered on time and to a high standard.
            </p>
          </div>


          {/* QR Generator */}
          <div className="flex flex-col gap-3">
            <h3 className="font-ibmPlexSerif text-xl text-primaryText">QR Code Generator</h3>
            <QRCodeGenerator />
            <p>
              I am adept at adapting to new tools and technologies, which enables me to remain competitive in Sdynamic work environments. My skill set is complemented by strong interpersonal attributes such as adaptability, self-motivation, and emotional intelligence, making me a reliable and accountable team member.
            </p>
          </div>

        </div>
    </div>
  );
}
