import type { Metadata } from "next";
// import localFont from "next/font/local";
import { IBM_Plex_Serif, Source_Code_Pro } from 'next/font/google'; // Import Source Code Pro from Google Fonts
import "./globals.css";


// Google font configuration for IBM Plex Serif
const ibmPlexSerif = IBM_Plex_Serif({
  weight: ['400', '500', '600', '700'], // Specify the weights you need
  subsets: ['latin'], // Specify the subsets you need
  variable: '--font-montserrat', // Optional: create a CSS variable for easy use
  display: 'swap', // Use 'swap' for better loading behavior
});

// Google font configuration for Source Code Pro
const sourceCodePro = Source_Code_Pro({
  weight: ['400', '500', '600', '700'], // Specify the weights you need
  subsets: ['latin'],
  variable: '--font-metrophobic', // Create a CSS variable for easy use
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSerif.variable} ${sourceCodePro.variable}  antialiased`} // Include font variables antialiased
      >
        {children}
      </body>
    </html>
  );
}
