import React from "react";
import type { Metadata } from "next";
import Footer from "@/components/footer";
import SkillBadge from "@/components/badges/badges";


export const metadata: Metadata = {
  title: "Taylor Steele",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <main className="flex flex-col flex-grow w-content gap-16 lg:gap-8">
        <div className="flex flex-col gap-4 items-start justify-between py-16 md:flex-row">
        {/* Headings and Nav */}
          <div className="flex flex-col gap-4 w-full md:w-1/2">
          {/* div containing headers */}
            <div className="flex flex-col gap-4"> 
              <h1 className="text-2xl font-ibmPlexSerif text-primaryText font-semibold lg:text-3xl">Taylor Steele</h1>
              <h2 className="text-lg font-sourceCodePro text-secondaryText"> Software Developer</h2>
            </div>
          </div>

          <div className="flex flex-col gap-8 w-full md:w-1/2">
          {/* Content */}
            <div className="flex flex-col gap-4 leading-relaxed text-base font-sourceCodePro text-secondaryText">
              <p className="text-sm leading-relaxed text-secondaryText">
               In 2022, I graduated from the University of Wisconsin - Stout with a B.S. in Digital Marketing Technology and minored in Computer Science. My degree empowered me with technical knowledge, marketing insights, which gave me the tools to deliver web solutions that are not only functional but also optimized for performance and SEO.
              </p>
              <p className="text-sm leading-relaxed text-secondaryText">
              After graduating, I worked at Nagios as a Web Developer, where I built WordPress sites with Elementor and created a custom shortcode plugin for server-side rendering to improve SEO and scalability. I also got to work with React.js and Faust.js, which really sparked my interest in modular frameworks and modern web development.
              </p>
              <p className="text-sm leading-relaxed text-secondaryText">
              I am a quick learner and adeptly able to adapt to new tools and technologies. This enables me to remain competitive in dynamic work environments and amongst my peers. My skill set is further rounded-out by my strong intrapersonal skills, self-motivation, emotional intelligence, ability to identify trends, and self-renewing ambition. I am a reliable, accountable, and personable asset to any team. 

              </p>
            </div>

            {/* Experience */}
            <div className="flex flex-col mt-6">
              {/* Nagios */}
              <a  href="https://www.nagios.com" target="_blank" rel="noreferrer noopener" aria-label="Web Developer at Nagios (opens in a new tab)">
                <div className="flex flex-col m-[-12px] p-4 gap-2 rounded-lg md:flex-row md:gap-8 hover:bg-gray-400 hover:bg-opacity-10 ">
                  {/* Timeline */}
                  <div className="flex flex-col md:w-1/3">
                    <span className="uppercase text-xs text-secondaryText font-sourceCodePro">2022 - 2024</span>
                  </div>
                  {/* Job Description */}
                  <div className="flex flex-col gap-2 md:w-2/3">
                    <span className="font-semibold text-sm font-ibmPlexSerif">Web Developer · Nagios</span>
                    <p className="text-xs text-secondaryText leading-normal mb-1 font-sourceCodePro">
                      Developed 4 websites, managed 8, built a headless WordPress site with Faust.js, and improved website health by 39% with technical SEO fixes.
                    </p> 
                    {/* libray, .com(x2), .org(x2), support(x2), ncpa  */}
                    {/* TODO: make components for this section */}
                    <ul className="flex flex-row flex-wrap gap-2">
                      <SkillBadge> HTML &amp; CSS </SkillBadge>
                      <SkillBadge> JavaScript </SkillBadge>
                      <SkillBadge> PHP </SkillBadge>
                      <SkillBadge> WordPress </SkillBadge>
                      <SkillBadge> GraphQL </SkillBadge>
                      <SkillBadge> React.js </SkillBadge>
                    </ul>

                  </div>
                </div>
              </a>
            </div>

          </div>
        </div>
      </main>
      
      <Footer />
    </>
  );
}
