import React from "react";
import type { Metadata } from "next";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Software Developer | Taylor Steele",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <main className="flex flex-col flex-grow w-content gap-16 lg:gap-8">
        <div className="flex flex-col gap-4 items-start justify-between py-16 md:flex-row">
        {/* Headings and Nav */}
          <div className="flex flex-col gap-4 w-full md:w-1/2">
          {/* div containing headers */}
            <div className="flex flex-col gap-4"> 
              <h1 className="text-2xl font-ibmPlexSerif text-primaryText font-semibold lg:text-3xl">Taylor Steele</h1>
              <h2 className="text-lg font-sourceCodePro text-secondaryText"> Software Engineer</h2>
            </div>
          </div>

          <div className="flex flex-col gap-8 w-full md:w-1/2">
          {/* Content */}
            <div className="flex flex-col gap-4 leading-relaxed text-base font-sourceCodePro text-secondaryText">
              <p className="text-sm leading-relaxed text-secondaryText">
                I am a dedicated and detail-oriented Web Developer with expertise in both front and back-end development. With a background in Digital Marketing Technology and a minor in Computer Science, I combine technical knowledge with marketing insight to deliver web solutions that are not only functional but also optimized for performance and SEO.
              </p>
              <p className="text-sm leading-relaxed text-secondaryText">
                I thrive in collaborative environments, consistently working cross-functionally to ensure projects are delivered on time and to a high standard.
              </p>
              <p className="text-sm leading-relaxed text-secondaryText">
                I am adept at adapting to new tools and technologies, which enables me to remain competitive in dynamic work environments. My skill set is complemented by strong interpersonal attributes such as adaptability, self-motivation, and emotional intelligence, making me a reliable and accountable team member.
              </p>
            </div>

            {/* Experience */}
            <div className="flex flex-col mt-6">
              {/* Nagios */}
              <a  href="https://www.nagios.com" target="_blank" rel="noreferrer noopener" aria-label="Web Developer at Nagios (opens in a new tab)">
                <div className="flex flex-col m-[-24px] p-4 gap-2 rounded-lg md:flex-row md:gap-8 hover:bg-gray-400 hover:bg-opacity-10 ">
                  {/* Timeline */}
                  <div className="flex flex-col md:w-1/3">
                    <span className="uppercase text-xs text-secondaryText font-sourceCodePro">2022 - 2024</span>
                  </div>
                  {/* Job Description */}
                  <div className="flex flex-col gap-2 md:w-2/3">
                    <span className="font-semibold text-sm font-ibmPlexSerif">Web Developer · Nagios</span>
                    <p className="text-xs text-secondaryText leading-normal mb-1 font-sourceCodePro">
                      Build, manage, and maintain websites.
                    </p>
                    {/* TODO: make components for this section */}
                    <ul className="flex flex-row flex-wrap gap-2">
                      <li className="flex items-center rounded-full bg-paleLilac px-2.5 py-0.5 text-xs font-medium leading-5 font-sourceCodePro text-[#1f223e]"> HTML &amp; CSS </li>
                      <li className="flex items-center rounded-full bg-paleLilac px-2.5 py-0.5 text-xs font-medium leading-5 font-sourceCodePro text-[#1f223e]"> JavaScript </li>
                      <li className="flex items-center rounded-full bg-paleLilac px-2.5 py-0.5 text-xs font-medium leading-5 font-sourceCodePro text-[#1f223e]"> PHP </li>
                      <li className="flex items-center rounded-full bg-paleLilac px-2.5 py-0.5 text-xs font-medium leading-5 font-sourceCodePro text-[#1f223e]"> WordPress </li>
                      <li className="flex items-center rounded-full bg-paleLilac px-2.5 py-0.5 text-xs font-medium leading-5 font-sourceCodePro text-[#1f223e]"> GraphQL </li>
                      <li className="flex items-center rounded-full bg-paleLilac px-2.5 py-0.5 text-xs font-medium leading-5 font-sourceCodePro text-[#1f223e]"> React.js </li>
                    </ul>

                  </div>
                </div>
              </a>
            </div>

          </div>
        </div>
      </main>
      
      <Footer />
    </>
  );
}
